registry="docker.io"
maintainer="jayjohnson"
basename="centos:7"
imagename="django-nginx"

export ENV_BASE_NGINX_CONFIG="/root/containerfiles/base_nginx.conf"
export ENV_DERIVED_NGINX_CONFIG="/root/containerfiles/non_ssl.conf"
export ENV_DEFAULT_ROOT_VOLUME="/opt/web"
export EXT_MOUNTED_VOLUME="/opt/web"
export INT_MOUNTED_VOLUME="/opt/web"
