registry="docker.io"
maintainer="jayjohnson"
basename="centos:7"
imagename="django-slack-sphinx"

ENV_BASE_HOMEDIR="/opt"
ENV_BASE_REPO_DIR="/opt/containerfiles/django"
ENV_BASE_DATA_DIR="/opt/containerfiles/django/data"
ENV_DEFAULT_ROOT_VOLUME="/opt/web"
ENV_DOC_SOURCE_DIR="/opt/web/django/blog/source"
ENV_DOC_OUTPUT_DIR="/opt/web/django/templates"
ENV_STATIC_OUTPUT_DIR="/opt/web/static"
ENV_MEDIA_DIR="/opt/web/media"
ENV_BASE_DOMAIN="jaypjohnson.com"
ENV_SLACK_BOTNAME="bugbot"
ENV_SLACK_CHANNEL="debugging"
ENV_SLACK_NOTIFY_USER="jay"
ENV_SLACK_TOKEN="xoxb-51351043345-Lzwmto5IMVb8UK36MghZYMEi"
ENV_SLACK_ENVNAME="djangoapp"
ENV_GOOGLE_ANALYTICS_CODE="UA-79840762-99"
ENV_DJANGO_DEBUG_MODE="True"
ENV_SERVER_MODE="DEV"
ENV_DEFAULT_PORT="80"
ENV_PROJ_DIR="/opt/containerfiles/django/wsgi/server/webapp"

